version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stereolink_app
    command: >
      bash -c "
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails genres:create &&
      bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/stereolink_development

  db:
    image: postgres:15
    container_name: stereolink_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stereolink_development
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  bundle_cache:
